import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
// this page creates all the children components in the projects
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App", // this is the name of the page in the browser tab
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // loads the html and body. Renders all the children 
    // usecase: If there is a need for an appbar, than this might be the place to add the contents (if it has to be added in all pages)

    <html lang="en">

      <body className={inter.className}> hi there{children}</body>
    </html>
  );
}
